package de.justinharder.powerlifting.model.domain.enums;

public enum Uebungskategorie
{
	ASSISTENZ_BRUST,
	ASSISTENZ_CORE,
	ASSISTENZ_GLUTEUS,
	ASSISTENZ_RUECKEN,
	ASSISTENZ_SCHULTER,
	ASSISTENZ_TRIZEPS,
	ASSISTENZ_UNTERARM,
	BANKDRUECKEN_VARIATION,
	KNIEBEUGE_VARIATION,
	KREUZHEBEN_VARIATION,
	UEBERKOPFDRUECKEN,
	WETTKAMPF_BANKDRUECKEN,
	WETTKAMPF_KNIEBEUGE,
	WETTKAMPF_KREUZHEBEN
}
