@startuml
entity Benutzer

entity Messung
{
    * **ID <<PK>>**
    * Datum
    * Koerpergewicht
    * KoerperfettAnteil
    * **BenutzerID <<FK>>**
}

entity Ziel
{
    * **ID <<PK>>**
    * Datum
    * Koerpergewicht
    * KoerperfettAnteil
    * **BenutzerID <<FK>>**
}

entity Hautfaltendicke
{
    * **ID <<PK>>**
    * Datum
    * Brustfalte
    * Bauchfalte
    * Beinfalte
    * Hueftfalte
    * Achselfalte
    * Trizepsfalte
    * Rueckenfalte
    * KoerperfettAnteil
    * **BenutzerID <<FK>>**
}

Benutzer ||--o{ Messung
Benutzer ||--o{ Ziel
Benutzer ||--o{ Hautfaltendicke
@enduml
