@startuml
entity Authentifizierung
{
    * **ID <<PK>>**
    * E-Mail-Adresse
    * Benutzername
    * Salt
    * Passwort
    * **BenutzerID <<FK>>**
}

entity Benutzer
{
    * **ID <<PK>>**
    * Nachname
    * Vorname
    * Geschlecht
    * Geburtsdatum
}

Benutzer ||--|| Authentifizierung
@enduml
